/*******************************************************************************
 *
 * Kewill ("COMPANY") CONFIDENTIAL
 *
 * Unpublished Copyright (c) 2009-2015 Kewill, All Rights Reserved.
 *
 * NOTICE: All information contained herein is, and remains the property of
 * COMPANY. The intellectual and technical concepts contained herein are
 * proprietary to COMPANY and may be covered by U.S. and Foreign Patents,
 * patents in process, and are protected by trade secret or copyright law.
 *
 * Dissemination of this information or reproduction of this material is
 * strictly forbidden unless prior written permission is obtained from COMPANY.
 * Access to the source code contained herein is hereby forbidden to anyone
 * except current, authorized COMPANY employees, managers or contractors who
 * have executed Confidentiality and Non-disclosure agreements explicitly
 * covering such access.
 *
 * The copyright notice above does not evidence any actual or intended
 * publication or disclosure of this source code, which includes information
 * that is confidential and/or proprietary, and is a trade secret, of COMPANY.
 *
 * ANY REPRODUCTION, MODIFICATION, DISTRIBUTION, PUBLIC  PERFORMANCE, OR PUBLIC
 * DISPLAY OF OR THROUGH USE OF THIS SOURCE CODE WITHOUT THE EXPRESS WRITTEN
 * CONSENT OF COMPANY IS STRICTLY PROHIBITED, AND IN VIOLATION OF APPLICABLE
 * LAWS AND INTERNATIONAL TREATIES. THE RECEIPT OR POSSESSION OF THIS SOURCE
 * CODE AND/OR RELATED INFORMATION DOES NOT CONVEY OR IMPLY ANY RIGHTS TO
 * REPRODUCE, DISCLOSE OR DISTRIBUTE ITS CONTENTS, OR TO MANUFACTURE, USE, OR
 * SELL ANYTHING THAT IT MAY DESCRIBE, IN WHOLE OR IN PART.
 *******************************************************************************/

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.19 at 03:05:15 PM IST 
//


package com.kewill.yms.domains.jaxb.appointmentoutbound;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;



/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SequenceNo">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="1"/>
 *               &lt;maxInclusive value="99"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="TruckNumber" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="TruckType" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="TruckOrigin" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="25"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="TruckDestination" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="25"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="IsConventionalTruck" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="DriverName" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DriverLicenseNumber" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DriverPhoneNumber" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DriverEmailId" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="320"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="IrregularArrival" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="IrregularArrivalRemarks" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4000"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="EntryAllowed" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="EntryNotAllowedReason" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4000"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="GateInRemarks" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4000"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="GateInDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="IrregularDeparture" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="IrregularDepartureRemarks" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4000"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ExitAllowed" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ExitNotAllowedReason" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4000"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="GateOutRemarks" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4000"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="GateOutDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="Remarks" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4000"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Flex1" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Flex2" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Flex3" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Flex4" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Flex5" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4000"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="FlexDate1" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="FlexDate2" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="FlexNo1" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="13"/>
 *               &lt;fractionDigits value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="FlexNo2" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="13"/>
 *               &lt;fractionDigits value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="FlexFlag1" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="MovementStatusCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MovementStatusDesc" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="400"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="StatusCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="StatusDesc" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="400"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Reserved" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element ref="{}CheckParams" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}TempGate" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}Trailer" maxOccurs="8" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sequenceNo",
    "truckNumber",
    "truckType",
    "truckOrigin",
    "truckDestination",
    "isConventionalTruck",
    "driverName",
    "driverLicenseNumber",
    "driverPhoneNumber",
    "driverEmailId",
    "irregularArrival",
    "irregularArrivalRemarks",
    "entryAllowed",
    "entryNotAllowedReason",
    "gateInRemarks",
    "gateInDateTime",
    "irregularDeparture",
    "irregularDepartureRemarks",
    "exitAllowed",
    "exitNotAllowedReason",
    "gateOutRemarks",
    "gateOutDateTime",
    "remarks",
    "flex1",
    "flex2",
    "flex3",
    "flex4",
    "flex5",
    "flexDate1",
    "flexDate2",
    "flexNo1",
    "flexNo2",
    "flexFlag1",
    "movementStatusCode",
    "movementStatusDesc",
    "statusCode",
    "statusDesc",
    "reserved",
    "checkParams",
    "tempGate",
    "trailer"
})
@XmlRootElement(name = "Truck")
public class Truck implements Serializable {
	  
	private static final long serialVersionUID=1L;

    @XmlElement(name = "SequenceNo")
    protected int sequenceNo;
    @XmlElement(name = "TruckNumber")
    protected String truckNumber;
    @XmlElement(name = "TruckType")
    protected String truckType;
    @XmlElement(name = "TruckOrigin")
    protected String truckOrigin;
    @XmlElement(name = "TruckDestination")
    protected String truckDestination;
    @XmlElement(name = "IsConventionalTruck")
    protected boolean isConventionalTruck;
    @XmlElement(name = "DriverName")
    protected String driverName;
    @XmlElement(name = "DriverLicenseNumber")
    protected String driverLicenseNumber;
    @XmlElement(name = "DriverPhoneNumber")
    protected String driverPhoneNumber;
    @XmlElement(name = "DriverEmailId")
    protected String driverEmailId;
    @XmlElement(name = "IrregularArrival")
    protected String irregularArrival;
    @XmlElement(name = "IrregularArrivalRemarks")
    protected String irregularArrivalRemarks;
    @XmlElement(name = "EntryAllowed")
    protected String entryAllowed;
    @XmlElement(name = "EntryNotAllowedReason")
    protected String entryNotAllowedReason;
    @XmlElement(name = "GateInRemarks")
    protected String gateInRemarks;
    @XmlElement(name = "GateInDateTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar gateInDateTime;
    @XmlElement(name = "IrregularDeparture")
    protected String irregularDeparture;
    @XmlElement(name = "IrregularDepartureRemarks")
    protected String irregularDepartureRemarks;
    @XmlElement(name = "ExitAllowed")
    protected String exitAllowed;
    @XmlElement(name = "ExitNotAllowedReason")
    protected String exitNotAllowedReason;
    @XmlElement(name = "GateOutRemarks")
    protected String gateOutRemarks;
    @XmlElement(name = "GateOutDateTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar gateOutDateTime;
    @XmlElement(name = "Remarks")
    protected String remarks;
    @XmlElement(name = "Flex1")
    protected String flex1;
    @XmlElement(name = "Flex2")
    protected String flex2;
    @XmlElement(name = "Flex3")
    protected String flex3;
    @XmlElement(name = "Flex4")
    protected String flex4;
    @XmlElement(name = "Flex5")
    protected String flex5;
    @XmlElement(name = "FlexDate1")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar flexDate1;
    @XmlElement(name = "FlexDate2")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar flexDate2;
    @XmlElement(name = "FlexNo1")
    protected BigDecimal flexNo1;
    @XmlElement(name = "FlexNo2")
    protected BigDecimal flexNo2;
    @XmlElement(name = "FlexFlag1")
    protected Boolean flexFlag1;
    @XmlElement(name = "MovementStatusCode")
    protected String movementStatusCode;
    @XmlElement(name = "MovementStatusDesc")
    protected String movementStatusDesc;
    @XmlElement(name = "StatusCode", required = true)
    protected String statusCode;
    @XmlElement(name = "StatusDesc")
    protected String statusDesc;
    @XmlElement(name = "Reserved")
    protected Boolean reserved;
    @XmlElement(name = "CheckParams")
    protected List<CheckParams> checkParams;
    @XmlElement(name = "TempGate")
    protected List<TempGate> tempGate;
    @XmlElement(name = "Trailer")
    protected List<Trailer> trailer;

    /**
     * Gets the value of the sequenceNo property.
     * 
     */
    public int getSequenceNo() {
        return sequenceNo;
    }

    /**
     * Sets the value of the sequenceNo property.
     * 
     */
    public void setSequenceNo(int value) {
        this.sequenceNo = value;
    }

    /**
     * Gets the value of the truckNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTruckNumber() {
        return truckNumber;
    }

    /**
     * Sets the value of the truckNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTruckNumber(String value) {
        this.truckNumber = value;
    }

    /**
     * Gets the value of the truckType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTruckType() {
        return truckType;
    }

    /**
     * Sets the value of the truckType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTruckType(String value) {
        this.truckType = value;
    }

    /**
     * Gets the value of the truckOrigin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTruckOrigin() {
        return truckOrigin;
    }

    /**
     * Sets the value of the truckOrigin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTruckOrigin(String value) {
        this.truckOrigin = value;
    }

    /**
     * Gets the value of the truckDestination property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTruckDestination() {
        return truckDestination;
    }

    /**
     * Sets the value of the truckDestination property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTruckDestination(String value) {
        this.truckDestination = value;
    }

    /**
     * Gets the value of the isConventionalTruck property.
     * 
     */
    public boolean isIsConventionalTruck() {
        return isConventionalTruck;
    }

    /**
     * Sets the value of the isConventionalTruck property.
     * 
     */
    public void setIsConventionalTruck(boolean value) {
        this.isConventionalTruck = value;
    }

    /**
     * Gets the value of the driverName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDriverName() {
        return driverName;
    }

    /**
     * Sets the value of the driverName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDriverName(String value) {
        this.driverName = value;
    }

    /**
     * Gets the value of the driverLicenseNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDriverLicenseNumber() {
        return driverLicenseNumber;
    }

    /**
     * Sets the value of the driverLicenseNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDriverLicenseNumber(String value) {
        this.driverLicenseNumber = value;
    }

    /**
     * Gets the value of the driverPhoneNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDriverPhoneNumber() {
        return driverPhoneNumber;
    }

    /**
     * Sets the value of the driverPhoneNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDriverPhoneNumber(String value) {
        this.driverPhoneNumber = value;
    }

    /**
     * Gets the value of the driverEmailId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDriverEmailId() {
        return driverEmailId;
    }

    /**
     * Sets the value of the driverEmailId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDriverEmailId(String value) {
        this.driverEmailId = value;
    }

    /**
     * Gets the value of the irregularArrival property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIrregularArrival() {
        return irregularArrival;
    }

    /**
     * Sets the value of the irregularArrival property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIrregularArrival(String value) {
        this.irregularArrival = value;
    }

    /**
     * Gets the value of the irregularArrivalRemarks property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIrregularArrivalRemarks() {
        return irregularArrivalRemarks;
    }

    /**
     * Sets the value of the irregularArrivalRemarks property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIrregularArrivalRemarks(String value) {
        this.irregularArrivalRemarks = value;
    }

    /**
     * Gets the value of the entryAllowed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntryAllowed() {
        return entryAllowed;
    }

    /**
     * Sets the value of the entryAllowed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntryAllowed(String value) {
        this.entryAllowed = value;
    }

    /**
     * Gets the value of the entryNotAllowedReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntryNotAllowedReason() {
        return entryNotAllowedReason;
    }

    /**
     * Sets the value of the entryNotAllowedReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntryNotAllowedReason(String value) {
        this.entryNotAllowedReason = value;
    }

    /**
     * Gets the value of the gateInRemarks property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGateInRemarks() {
        return gateInRemarks;
    }

    /**
     * Sets the value of the gateInRemarks property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGateInRemarks(String value) {
        this.gateInRemarks = value;
    }

    /**
     * Gets the value of the gateInDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getGateInDateTime() {
        return gateInDateTime;
    }

    /**
     * Sets the value of the gateInDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setGateInDateTime(XMLGregorianCalendar value) {
        this.gateInDateTime = value;
    }

    /**
     * Gets the value of the irregularDeparture property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIrregularDeparture() {
        return irregularDeparture;
    }

    /**
     * Sets the value of the irregularDeparture property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIrregularDeparture(String value) {
        this.irregularDeparture = value;
    }

    /**
     * Gets the value of the irregularDepartureRemarks property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIrregularDepartureRemarks() {
        return irregularDepartureRemarks;
    }

    /**
     * Sets the value of the irregularDepartureRemarks property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIrregularDepartureRemarks(String value) {
        this.irregularDepartureRemarks = value;
    }

    /**
     * Gets the value of the exitAllowed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExitAllowed() {
        return exitAllowed;
    }

    /**
     * Sets the value of the exitAllowed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExitAllowed(String value) {
        this.exitAllowed = value;
    }

    /**
     * Gets the value of the exitNotAllowedReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExitNotAllowedReason() {
        return exitNotAllowedReason;
    }

    /**
     * Sets the value of the exitNotAllowedReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExitNotAllowedReason(String value) {
        this.exitNotAllowedReason = value;
    }

    /**
     * Gets the value of the gateOutRemarks property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGateOutRemarks() {
        return gateOutRemarks;
    }

    /**
     * Sets the value of the gateOutRemarks property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGateOutRemarks(String value) {
        this.gateOutRemarks = value;
    }

    /**
     * Gets the value of the gateOutDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getGateOutDateTime() {
        return gateOutDateTime;
    }

    /**
     * Sets the value of the gateOutDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setGateOutDateTime(XMLGregorianCalendar value) {
        this.gateOutDateTime = value;
    }

    /**
     * Gets the value of the remarks property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * Sets the value of the remarks property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemarks(String value) {
        this.remarks = value;
    }

    /**
     * Gets the value of the flex1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlex1() {
        return flex1;
    }

    /**
     * Sets the value of the flex1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlex1(String value) {
        this.flex1 = value;
    }

    /**
     * Gets the value of the flex2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlex2() {
        return flex2;
    }

    /**
     * Sets the value of the flex2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlex2(String value) {
        this.flex2 = value;
    }

    /**
     * Gets the value of the flex3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlex3() {
        return flex3;
    }

    /**
     * Sets the value of the flex3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlex3(String value) {
        this.flex3 = value;
    }

    /**
     * Gets the value of the flex4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlex4() {
        return flex4;
    }

    /**
     * Sets the value of the flex4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlex4(String value) {
        this.flex4 = value;
    }

    /**
     * Gets the value of the flex5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlex5() {
        return flex5;
    }

    /**
     * Sets the value of the flex5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlex5(String value) {
        this.flex5 = value;
    }

    /**
     * Gets the value of the flexDate1 property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFlexDate1() {
        return flexDate1;
    }

    /**
     * Sets the value of the flexDate1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFlexDate1(XMLGregorianCalendar value) {
        this.flexDate1 = value;
    }

    /**
     * Gets the value of the flexDate2 property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFlexDate2() {
        return flexDate2;
    }

    /**
     * Sets the value of the flexDate2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFlexDate2(XMLGregorianCalendar value) {
        this.flexDate2 = value;
    }

    /**
     * Gets the value of the flexNo1 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFlexNo1() {
        return flexNo1;
    }

    /**
     * Sets the value of the flexNo1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFlexNo1(BigDecimal value) {
        this.flexNo1 = value;
    }

    /**
     * Gets the value of the flexNo2 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFlexNo2() {
        return flexNo2;
    }

    /**
     * Sets the value of the flexNo2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFlexNo2(BigDecimal value) {
        this.flexNo2 = value;
    }

    /**
     * Gets the value of the flexFlag1 property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFlexFlag1() {
        return flexFlag1;
    }

    /**
     * Sets the value of the flexFlag1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFlexFlag1(Boolean value) {
        this.flexFlag1 = value;
    }

    /**
     * Gets the value of the movementStatusCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMovementStatusCode() {
        return movementStatusCode;
    }

    /**
     * Sets the value of the movementStatusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMovementStatusCode(String value) {
        this.movementStatusCode = value;
    }

    /**
     * Gets the value of the movementStatusDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMovementStatusDesc() {
        return movementStatusDesc;
    }

    /**
     * Sets the value of the movementStatusDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMovementStatusDesc(String value) {
        this.movementStatusDesc = value;
    }

    /**
     * Gets the value of the statusCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatusCode() {
        return statusCode;
    }

    /**
     * Sets the value of the statusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatusCode(String value) {
        this.statusCode = value;
    }

    /**
     * Gets the value of the statusDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatusDesc() {
        return statusDesc;
    }

    /**
     * Sets the value of the statusDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatusDesc(String value) {
        this.statusDesc = value;
    }

    /**
     * Gets the value of the reserved property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isReserved() {
        return reserved;
    }

    /**
     * Sets the value of the reserved property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setReserved(Boolean value) {
        this.reserved = value;
    }

    /**
     * Gets the value of the checkParams property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the checkParams property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCheckParams().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CheckParams }
     * 
     * 
     */
    public List<CheckParams> getCheckParams() {
        if (checkParams == null) {
            checkParams = new ArrayList<CheckParams>();
        }
        return this.checkParams;
    }

    /**
     * Gets the value of the tempGate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tempGate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTempGate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TempGate }
     * 
     * 
     */
    public List<TempGate> getTempGate() {
        if (tempGate == null) {
            tempGate = new ArrayList<TempGate>();
        }
        return this.tempGate;
    }

    /**
     * Gets the value of the trailer property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the trailer property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTrailer().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Trailer }
     * 
     * 
     */
    public List<Trailer> getTrailer() {
        if (trailer == null) {
            trailer = new ArrayList<Trailer>();
        }
        return this.trailer;
    }

}